server:
  port: 8080

spring:
  application:
    name: agri-bridge
  datasource:
    url: jdbc:mysql://localhost:3306/agri_bridge?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: ab123168
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

app:
  jwt:
    secret: "change-me-please-please-change-me-32"
    expire-minutes: 720
    issuer: "agri-bridge"
